<?php
/**
 * Created by JetBrains PhpStorm.
 * User: cinfante
 * Date: 06/07/13
 * Time: 01:51 PM
 * To change this template use File | Settings | File Templates.
 */

namespace Planillas\CoreBundle\Validator\Constraints;

use Symfony\Component\Validator\Constraint;

/**
 * Class CedulaValida
 * @package Planillas\CoreBundle\Validator\Constraints
 * @Annotation
 */
class CedulaValida extends Constraint
{
    public $mensaje = 'La cédula no es correcta.';
    //public $messagePin = 'El Pin proporcionado no es válido.';

    public function getTargets()
    {
        return self::CLASS_CONSTRAINT;
    }

    public function validatedBy()
    {
        return 'codigoYpin_validador'; // TODO: Change the autogenerated stub
    }

}
