<?php

namespace Planillas\CoreBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CEmpleadoReferenciaLaboralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CEmpleadoReferenciaLaboralRepository extends EntityRepository
{
}
