<?php

namespace Planillas\CoreBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CEmpleadoReferenciaLaboralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CEmpleadoReferenciasRepository extends EntityRepository
{
    public function deleteReferenciaById($id)
    {
        $dql = 'DELETE FROM CEmpleadoReferencias r WHERE r.id = :id';

        $query = $this->createQueryBuilder('r')
            ->delete('PlanillasCoreBundle:CEmpleadoReferencias', 'r')
            ->where('r.id = :id')
            ->getQuery()
            ->setParameter('id', $id);

        try {
            $query->execute();

            return true;
        } catch (\Exception $e) {
            // log exception
            //print_r($e->getMessage());exit;
            return false;
        }
    }
}
