<?php

namespace Planillas\CoreBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CEmpleadoReferenciaPersonalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CEmpleadoReferenciaPersonalRepository extends EntityRepository
{
}
