planillas_payments:
    resource: "@PlanillasPaymentsBundle/Resources/config/routing.yml"
    prefix:   /payments

#planillas_template:
#    resource: "@PlanillasTemplateBundle/Resources/config/routing.yml"
#    prefix:   /

planillas_entidades:
    resource: "@PlanillasEntidadesBundle/Resources/config/routing.yml"
    prefix:   /entidad

planillas_nomenclador:
    resource: "@PlanillasNomencladorBundle/Resources/config/routing.yml"
    prefix:   /nomenclador

planillas_core:
    resource: "@PlanillasCoreBundle/Resources/config/routing.yml"
    prefix:   /

# friendofsymfony js routing bundle
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"