<?php

namespace Planillas\EntidadesBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ECuentaBancoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ECuentaBancoRepository extends EntityRepository
{
}
