<?php

namespace Planillas\EstructuraBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BonificacionesEnPuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonificacionesEnPuestoRepository extends EntityRepository
{
}
