<?php

namespace Planillas\EstructuraBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * RolesPuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolesPuestoRepository extends AbstractRepository
{
    public function findAllNotDeleted ($filters = array())
    {
        $dql = "SELECT r FROM PlanillasEstructuraBundle:RolesPuesto r";

        $dql = $this->addParamsToDql($dql, 'r', $filters);

        $dql.=" ORDER BY r.id DESC";

        $query = $this->_em->createQuery($dql);
        $query = $this->addParamsToQuery($query, $filters);

        return $query;
    }

    public function findAllByPuestoId($id)
    {
        $query = $this->findAllNotDeleted(array(
            'puesto' => $id,
        ));

        try {
            return $query->getResult();
        } catch (NoResultException $e) {
            return array();
        }
    }
}
