estructura_puesto_index:
  path: /
  defaults: { _controller: "PlanillasEstructuraBundle:Puesto:index" }

estructura_puesto_list:
  path: /list
  defaults: { _controller: "PlanillasEstructuraBundle:Puesto:list" }
  options:
    expose: true

estructura_puesto_create:
  path: /create
  defaults: { _controller: "PlanillasEstructuraBundle:Puesto:create" }
  requirements: { _method: post }
  options:
    expose: true

estructura_puestos:
  path: /{id}/puestos
  defaults: { _controller: "PlanillasEstructuraBundle:Puesto:puestosCombo" }
  options:
    expose: true

estructura_puesto_detalles:
  path: /{id}/detalles
  defaults: { _controller: "PlanillasEstructuraBundle:Puesto:puestoDetalles" }
  options:
    expose: true
