empleado_referencias:
    pattern: /
    defaults: { _controller: "PlanillasCoreBundle:CEmpleadoReferencias:index" }

empleado_referencias_new:
    pattern: /new
    defaults: { _controller: "PlanillasCoreBundle:CEmpleadoReferencias:new" }

empleado_referencias_create:
    pattern: /create
    defaults: { _controller: "PlanillasCoreBundle:CEmpleadoReferencias:create" }

empleado_referencias_edit:
    pattern: /{id}/edit
    defaults: { _controller: "PlanillasCoreBundle:CEmpleadoReferencias:edit" }

empleado_referencias_update:
    pattern: /{id}/update
    defaults: { _controller: "PlanillasCoreBundle:CEmpleadoReferencias:update" }
    requirements: { _method: 'PUT' }

empleado_referencias_delete:
    pattern: /delete
    defaults: { _controller: "PlanillasCoreBundle:CEmpleadoReferencias:delete" }
    requirements: { _method: 'DELETE' }