empleado_index:
    pattern:   /
    defaults: { _controller: "PlanillasCoreBundle:CEmpleado:index" }

empleado_show:
    pattern:   /empleado/{id}/show
    defaults: { _controller: "PlanillasCoreBundle:CEmpleado:show" }

empleado_update:
    pattern:   /empleado/{id}/update
    defaults: { _controller: "PlanillasCoreBundle:CEmpleado:update" }

empleado_new:
    pattern:   /empleado/new
    defaults: { _controller: "PlanillasCoreBundle:CEmpleado:new" }

empleado_create:
    pattern:   /empleado/create
    defaults: { _controller: "PlanillasCoreBundle:CEmpleado:create" }

empleado_edit:
    pattern:   /empleado/{id}/edit
    defaults: { _controller: "PlanillasCoreBundle:CEmpleado:edit" }

empleado_activar:
    pattern:   /empleado/{id}
    defaults: { _controller: "PlanillasCoreBundle:CEmpleado:activar" }

empleado_delete:
    pattern:   /empleado/{id}/delete
    defaults: { _controller: "PlanillasCoreBundle:CEmpleado:delete" }

empleado_foto:
    pattern:   /empleado/{id}/foto
    defaults: { _controller: "PlanillasCoreBundle:CEmpleado:updatePhoto" }

cpagos:
    pattern:   /planillas
    defaults: { _controller: "PlanillasCoreBundle:CPlanillas:buscar" }

cplanillas_buscar:
    pattern:   /planillas/pagos
    defaults: { _controller: "PlanillasCoreBundle:CPlanillas:pagos" }

cplanillas_create:
    pattern: /planillas/create
    defaults: { _controller: "PlanillasCoreBundle:CPlanillas:createPlanilla" }
    requirements: { _method: post }

cplanillas_listar:
    pattern:   /planillas/listar
    defaults: { _controller: "PlanillasCoreBundle:CPlanillas:listar" }

cplanillas_detalles:
    pattern:   /planillas/{id}/detalles
    defaults: { _controller: "PlanillasCoreBundle:CPlanillas:detalles" }

cplanillas_reporte:
    pattern:   /planillas/reporte
    defaults: { _controller: "PlanillasCoreBundle:CPlanillas:reporte" }
