planillas_core_homepage:
    pattern:  /
    defaults: { _controller: "PlanillasCoreBundle:Default:index" }

planillas_core_empleados:
    resource: "@PlanillasCoreBundle/Resources/config/routing/empleado.yml"
    prefix:   /empleado

planillas_core_domicilio:
    resource: "@PlanillasEntidadesBundle/Resources/config/routing/edomicilio.yml"
    prefix:   /empleado/domicilio

planillas_core_antecedente_penal:
    resource: "@PlanillasEntidadesBundle/Resources/config/routing/eantecedentepenal.yml"
    prefix:   /empleado/antecedentepenal

planillas_core_cursos:
    resource: "@PlanillasEntidadesBundle/Resources/config/routing/ecursos.yml"
    prefix:   /empleado/curso

planillas_core_dato_legal:
    resource: "@PlanillasEntidadesBundle/Resources/config/routing/edatolegal.yml"
    prefix:   /empleado/datolegal

planillas_core_educacion:
    resource: "@PlanillasEntidadesBundle/Resources/config/routing/eeducacion.yml"
    prefix:   /empleado/educacion

planillas_core_idiomas:
    resource: "@PlanillasEntidadesBundle/Resources/config/routing/eeducacionidiomas.yml"
    prefix:   /empleado/idiomas

planillas_core_familia:
    resource: "@PlanillasEntidadesBundle/Resources/config/routing/efamilia.yml"
    prefix:   /empleado/familia

planillas_core_persona_depende:
    resource: "@PlanillasEntidadesBundle/Resources/config/routing/epersonadependen.yml"
    prefix:   /empleado/

planillas_core_historia_trabajo:
    resource: "@PlanillasEntidadesBundle/Resources/config/routing/ehistoriatrabajo.yml"
    prefix:   /empleado/

planillas_core_salario:
    resource: "@PlanillasCoreBundle/Resources/config/routing/csalariobase.yml"
    prefix:   /empleado/

planillas_entidades_componentes_salariales:
    resource: "@PlanillasEntidadesBundle/Resources/config/routing/ecomponentessalariales.yml"
    prefix:   /empleado/

planillas_core_trabajo:
    resource: "@PlanillasCoreBundle/Resources/config/routing/ctrabajo.yml"
    prefix:   /empleado/

planillas_core_licencias:
    resource: "@PlanillasEntidadesBundle/Resources/config/routing/elicencia.yml"
    prefix:   /empleado/licencias

planillas_core_vacante:
    resource: "@PlanillasCoreBundle/Resources/config/routing/cvacante.yml"
    prefix:   /trabajo/
planillas_core_solicitud_empleo:
    resource: "@PlanillasCoreBundle/Resources/config/routing/csolicitudempleo.yml"
    prefix:   /solicitudes/

planillas_core_horario:
    resource: "@PlanillasCoreBundle/Resources/config/routing/chorario.yml"
    prefix:   /horario/

planillas_core_ausencias:
    resource: "@PlanillasCoreBundle/Resources/config/routing/causencias.yml"
    prefix:   /ausencias/

planillas_core_historias_salud:
    resource: "@PlanillasEntidadesBundle/Resources/config/routing/ehistoriasalud.yml"
    prefix:   /empleado/historiasalud

planillas_core_cuentas_bancos:
    resource: "@PlanillasEntidadesBundle/Resources/config/routing/ecuentabanco.yml"
    prefix:   /empleado/cuentasbanco

planillas_core_horas_extras:
    resource: "@PlanillasCoreBundle/Resources/config/routing/chorasextras.yml"
    prefix:   /extras/

planillas_core_incapacidades:
    resource: "@PlanillasCoreBundle/Resources/config/routing/cincapacidades.yml"
    prefix:   /incapacidades/

planillas_core_deudas:
    resource: "@PlanillasCoreBundle/Resources/config/routing/cdeudas.yml"
    prefix:   /deudas/

planillas_core_incapacidades:
    resource: "@PlanillasCoreBundle/Resources/config/routing/cincapacidades.yml"
    prefix:   /incapacidades/

planillas_core_dias_extra:
    resource: "@PlanillasCoreBundle/Resources/config/routing/cdiasextra.yml"
    prefix:   /dias-extra/

planillas_core_componentes_salariales:
    resource: "@PlanillasCoreBundle/Resources/config/routing/componentessalariales.yml"
    prefix: /compsalariales

planillas_core_empleado_referencias:
    resource: "@PlanillasCoreBundle/Resources/config/routing/cempleadoreferencias.yml"
    prefix: /empleado/{id_empleado}/referencias

planillas_core_empleado_basedatos_digital:
    resource: "@PlanillasCoreBundle/Resources/config/routing/cempleadobasedatosdigital.yml"
    prefix: /empleado/{id_empleado}/bddigital

planillas_core_empleado_hoja_delincuencia:
    resource: "@PlanillasCoreBundle/Resources/config/routing/cempleadohojadelincuencia.yml"
    prefix: /empleado/{id_empleado}/hojadelincuencia

planillas_core_empleaso_cartas_recomendacion:
    resource: "@PlanillasCoreBundle/Resources/config/routing/cempleadocartasrecomendacion.yml"
    prefix: /empleado/{id_empleado}/cartasrecomendacion
