parameters:
    planillas.core.empleado.manager: Planillas\CoreBundle\Form\Managers\EmpleadoManager

services:
    core.cplanillas.manager:
        class: Planillas\CoreBundle\Managers\CPlanillasManagers
        arguments: [@service_container]

    core.empleado.manager:
        class: %planillas.core.empleado.manager%
        arguments:
            - @doctrine.orm.entity_manager

    core.salario_base_puesto.handler:
        class: Planillas\CoreBundle\Form\Handlers\SalarioBasePuestoHandler
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory
            - @router
            - @logger
